// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qskayneqqyysskwodlyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFza2F5bmVxcXl5c3Nrd29kbHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzQyMDAsImV4cCI6MjA3NDkxMDIwMH0.MixZ96oLJsA3rMJRSBfdZ9kYytAHeyBGkhjW7aP4RpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);